plugins {
    id 'io.github.gradle-nexus.publish-plugin' version '1.1.0'
}

allprojects {
    buildscript {
        ext {
            minSdkVersion = 26
            targetSdkVersion = 34
            compileSdkVersion = 34
            buildToolsVersion = '34.0.0'
            ndkVersion = '28.2.13676358'

            coreVersion = "1.4.0"
            extJUnitVersion = "1.2.1"
            runnerVersion = "1.4.0"
            rulesVersion = "1.4.0"
            junitVersion = "4.12"

            fbjniJavaOnlyVersion = "0.2.2"
            soLoaderNativeLoaderVersion = "0.10.5"
        }

        repositories {
            google()
            mavenLocal()
            mavenCentral()
        }

        dependencies {
            classpath 'com.android.tools.build:gradle:8.5.1'
        }
    }

    repositories {
        google()
        mavenCentral()
    }
}

ext.deps = [
        jsr305: 'com.google.code.findbugs:jsr305:3.0.1',
]

// Stub secrets to let the project sync and build without the publication values set up
ext["ossrhUsername"] = null
ext["ossrhPassword"] = null

// Grabbing secrets from environment variables
ext["ossrhUsername"] = System.getenv("OSSRH_USERNAME")
ext["ossrhPassword"] = System.getenv("OSSRH_PASSWORD")

def getExtraString(name) { return ext[name]?.toString() }

nexusPublishing {
    repositories {
        sonatype {
            nexusUrl = uri("https://ossrh-staging-api.central.sonatype.com/service/local/")
            snapshotRepositoryUrl = uri("https://central.sonatype.com/repository/maven-snapshots/")
            username = getExtraString("ossrhUsername")
            password = getExtraString("ossrhPassword")
        }
    }
}
