allprojects {
    buildscript {
        ext {
            minSdkVersion = 26
            targetSdkVersion = 34
            compileSdkVersion = 34
            buildToolsVersion = '34.0.0'
            ndkVersion = '28.2.13676358'

            coreVersion = "1.4.0"
            extJUnitVersion = "1.2.1"
            runnerVersion = "1.4.0"
            rulesVersion = "1.4.0"
            junitVersion = "4.12"

            fbjniJavaOnlyVersion = "0.2.2"
            soLoaderNativeLoaderVersion = "0.10.5"
        }

        repositories {
            google()
            mavenLocal()
            mavenCentral()
        }

        dependencies {
            classpath 'com.android.tools.build:gradle:8.5.1'
        }
    }

    repositories {
        google()
        mavenCentral()
    }
}

ext.deps = [
        jsr305: 'com.google.code.findbugs:jsr305:3.0.1',
]
