ABI_FILTERS=armeabi-v7a,arm64-v8a,x86,x86_64

VERSION_NAME=2.8.0-SNAPSHOT
GROUP=de.voize.pytorch
MAVEN_GROUP=de.voize.pytorch
SONATYPE_STAGING_PROFILE=de.voize.pytorch
POM_ARTIFACT_ID=pytorch_android_lite
POM_URL=https://github.com/voize-gmbh/pytorch/tree/master/android
POM_SCM_URL=https://github.com/voize-gmbh/pytorch.git
POM_SCM_CONNECTION=scm:git:https://github.com/voize-gmbh/pytorch
POM_SCM_DEV_CONNECTION=scm:git:git@github.com:voize-gmbh/pytorch.git
POM_LICENSE_NAME=BSD 3-Clause
POM_LICENSE_URL=https://github.com/voize-gmbh/pytorch/blob/master/LICENSE
POM_ISSUES_URL=https://github.com/voize-gmbh/pytorch/issues
POM_LICENSE_DIST=repo
POM_DEVELOPER_ID=pytorch
POM_DEVELOPER_NAME=pytorch

# Gradle internals
org.gradle.internal.repository.max.retries=1
org.gradle.jvmargs=-XX:MaxMetaspaceSize=1024m

android.useAndroidX=true
android.enableJetifier=true

nativeLibsDoNotStrip=false
testAppAllVariantsEnabled=false
